x-openedx-job-service:
  &openedx-job-service
  image: openedx-dev:19.0.2
  build:
    context: ../build/openedx/
    target: development
    args:
      # Note that we never build the openedx-dev image with root user ID, as it would simply fail.
      APP_USER_ID: "1000"
  volumes:
    # Settings & config
    - ../apps/openedx/settings/lms:/openedx/edx-platform/lms/envs/tutor:ro
    - ../apps/openedx/settings/cms:/openedx/edx-platform/cms/envs/tutor:ro
    - ../apps/openedx/config:/openedx/config:ro
    # theme files
    - ../build/openedx/themes:/openedx/themes

services:

  lms-job:
    <<: *openedx-job-service

  cms-job:
    <<: *openedx-job-service

  